### ISSUE TITLE
stock_operation_type_location

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/stock-logistics-warehouse#1]
Acceptance criteria:
- [ ] Penambahan field allowed_location_ids pada stock.picking.type
- [ ] Penambahan field allowed_dest_location_ids pada stock.picking.type
- [ ] Filter location_id pada stock.move sesuai dengan nilai picking_type_id pada stock.picking
- [ ] Filter dest_location_id pada stock.move sesuai dengan nilai picking_type_id pada stock.picking

**Comment by andhit-r** [comment]
cc @azmimr67

**Comment by andhit-r** [comment]
@mikevhe18 sambil nunggu proses event_contact_person di review, kerjain ini dulu yah mike.

**Comment by mikevhe18** [comment]
PR TO OCA [#162](https://github.com/OCA/stock-logistics-warehouse/pull/162)
